services:
  api:
    image: batuergun/terraweb:${GITHUB_SHA}
    environment:
      - API_KEY=${API_KEY}
      - PYTHONPATH=/app
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.costerra.co/fullchain.pem:/etc/letsencrypt/live/api.costerra.co/fullchain.pem:ro
      - /etc/letsencrypt/live/api.costerra.co/privkey.pem:/etc/letsencrypt/live/api.costerra.co/privkey.pem:ro
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: "https://kali.assos.cloud/grafana"
    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc)($$|/)'

volumes:
  grafana_data:
  prometheus_data: