name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push API Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./api
        push: true
        tags: batuergun/terraweb:${{ github.sha }}

    - name: Prepare deployment files
      run: |
        mkdir -p deploy
        cp docker-compose.yml deploy/
        cp nginx.conf deploy/
        cp prometheus.yml deploy/
        # Add any other necessary files here

    - name: Upload deployment artifact
      uses: actions/upload-artifact@v4
      with:
        name: deploy-package
        path: deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download deployment artifact
      uses: actions/download-artifact@v4
      with:
        name: deploy-package

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      env:
        API_KEY: ${{ secrets.API_KEY }}
        GITHUB_SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: github-deploy
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        envs: API_KEY,GITHUB_SHA
        script: |
          # Clone the repo if it doesn't exist, otherwise pull latest changes
          if [ ! -d "/opt/terraWeb" ]; then
            git clone https://github.com/batuergun/terraweb.git /opt/terraWeb
          else
            cd /opt/terraWeb
            git pull
          fi

          cd /opt/terraWeb

          # Update .env file
          echo "API_KEY=$API_KEY" > .env
          echo "GITHUB_SHA=$GITHUB_SHA" >> .env
          
          # Deploy with Docker Compose
          docker compose pull
          docker compose up -d
          
          echo "Deployment completed successfully"